### ISSUE TITLE
presentation is too dense

### ISSUE THREAD

**Issue by emckean** [IBM/kube101#11]
The "Kubernetes Resource Model" slide in the presentation is way too dense. I think it needs to be split into multiple slides so that people can grasp the material. 

For the workshop last week I did split it out into multiple slides -- attached in case it's helpful: 
[Kube-101-all.pptx](https://github.com/IBM/kube101/files/1880897/Kube-101-all.pptx)

**Comment by MHBauer** [comment]
I agree, I think the argument for that slide was, "there's a lot of other capability, but we're only going to talk about xyz" I think some of the added expanded slides go into things that aren't even in the material at all.

**Comment by emckean** [comment]
You're probably right -- depends on the goal of the presentation. Are we giving an detailed overview, or just enough to get through the example? Might need a set of "accordion" slides that can expand or contract depending on length of presentation, whether it's hands-on or lecture, etc. :)

**Comment by MHBauer** [comment]
@emckean is there any builtin functionality to powerpoint for this accordion type of operation? We've been looking for just that kind of functionality in lots of tools for a long time.

**Comment by emckean** [comment]
You can do this with Reveal.js -- they have a "vertical slides" function so
you can go forward and back and "up and down" so you can literally drill
down on a topic. :)

**Comment by MHBauer** [comment]
looks neat. Looks like it can run locally as well, which is necessary. @duglin WDYT?

**Comment by remkohdev** [comment]
expired, please recreate issue if this still exists in the current version
