### ISSUE TITLE
bad link

### ISSUE THREAD

**Issue by MHBauer** [IBM/kube101#21]
we have a 404 on workshop/README.md

https://ace-docs-production-red.ng.bluemix.net/docs/api/content/homepage/images/containerServiceIcon.svg

**Comment by MHBauer** [comment]
https://github.com/IBM/kube101/blame/master/workshop/README.md#L1

I do not know what it should be to fix it.

**Comment by duglin** [comment]
Go ahead an open a PR to just remove it
