### ISSUE TITLE
the README is lacking anything substantial

### ISSUE THREAD

**Issue by stevemart** [IBM/kube101#4]
the README is not even a complete sentence.

**Comment by krook** [comment]
Well, if you look at it from a Kubernetes point of view, it kind of make sense, in a meta way @stevemart.

**Comment by jkomg** [comment]
where we're going we don't need complete sentences

**Comment by jkomg** [comment]
fixed

**Comment by stevemart** [comment]
it is?

**Comment by jkomg** [comment]
I do think we need to put in something more descriptive of the contents of the repo.

**Comment by stevemart** [comment]
i 'spose

**Comment by duglin** [comment]
Appears to be fixed.
