### ISSUE TITLE
teach people how to set kubeconfig and path

### ISSUE THREAD

**Issue by MHBauer** [IBM/kube101#40]
is was a huge problem in actual practice. We need to add the details on how to do this on linux and windows.

export KUBECONFIG=bleh
&
$env:KUBECONFIG = bleh
something like that anyway, I don't have windows to test.

**Comment by timroster** [comment]
Yes, we saw this too in a workshop. On windows when using cmd or powershell, the `ibmcloud cs cluster-config <clustername>` command returns something like:
`set KUBECONFIG=bleh` 
regardless of the shell being used. Copy/paste of this to cmd works, but for powershell this needs to be changed to:
`$env:KUBECONFIG=bleh`
for kubectl to access the IKS cluster.

**Comment by remkohdev** [comment]
expired, please recreate issue if this still exists in the current version
